### ISSUE TITLE
SurfaceEigenstrapping str or array

### ISSUE THREAD

**Issue by jordandekraker** [SNG-Newy/eigenstrapping#4] opened 2024-04-09 17:55 UTC
Hi,

Thanks for this awesome tool. I'm following Tutorial 3 to generate my own surrogate maps and I can't determine whether `SurfaceEigenstrapping` requires an array or a string:

```
AttributeError                            Traceback (most recent call last)
Input In [82], in <module>
      1 from eigenstrapping import SurfaceEigenstrapping
----> 2 t = SurfaceEigenstrapping(surface='../tpl-avg_space-canonical_den-1mm_label-hipp_midthickness.surf.gii'
      3                               ,data='../thickness_midsurf_L_mean.shape.gii', num_modes=200)

File /export03/data/opt/venv/lib/python3.8/site-packages/eigenstrapping/base.py:329, in SurfaceEigenstrapping.__init__(self, data, surface, evals, emodes, num_modes, save_surface, seed, decomp_method, medial, randomize, resample, n_jobs, use_cholmod, permute, add_res, save_rotations, parcellation, normalize)
    326     self.surface = load_surface(self.surface_file)
    328 self.data = copy.deepcopy(data)
--> 329 self.n_vertices = self.data.shape[0]
    331 if emodes is not None and evals is not None:
    332     self.evals = evals[:num_modes]

AttributeError: 'str' object has no attribute 'shape'
```

input files here:
https://github.com/MICA-MNI/hippomaps/blob/master/resources/canonical_surfs/tpl-avg_space-canonical_den-1mm_label-hipp_midthickness.surf.gii
https://github.com/MICA-MNI/hippomaps/blob/master/hippomaps/example_data/thickness_midsurf_L_mean.shape.gii

Thanks!

**Comment by nikitas-k** [comment] 2024-04-09 23:39
Hi Jordan, thanks for checking it out! I really should get around to rewriting Tutorial 3, it's gone stale.

As for your issue, the `SurfaceEigenstrapping` class as intended really should be able to handle surfaces and data inputs in both str and array format, so this is probably just bad coding on my part. I'll fix this as soon as possible.

**Comment by nikitas-k** [comment] 2024-04-10 02:14
This was really just a sloppy error on my part, see the commit above. Should be working now, so I'll go ahead and close this. Feel free to reopen if you're still getting the error.

**Closed by nikitas-k** 2024-04-10 02:14 UTC

**Comment by jordandekraker** [comment] 2024-04-10 16:31
Solved, thanks!

I believe my wrapper in HippoMaps is working correctly, but if you have the time then feel free to take a look here: https://github.com/jordandekraker/hippomaps/pull/10
